name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==3.8.0
      - cloudpickle
      - numpy
      - pandas
      - pyarrow
      - scikit-learn
      - scipy
